apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akstest-152a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akstest-152a"
  template:
    metadata:
      labels:
        app: "akstest-152a"
    spec:
      containers:
        - name: "akstest-152a"
          image: "aksbala.azurecr.io/akstest"
          ports:
          - containerPort: 80