apiVersion: v1
kind: Service
metadata:
    name: "akstest-152a"
    labels:
        app: "akstest-152a"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akstest-152a"